<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_day</name>
   <tag></tag>
   <elementGuidId>02e3bc2f-eb18-4a89-9c33-8c8a2fe87002</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.day:not(.old)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>b8b66692-646f-4a49-87a5-9f217f1dd66a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1673010883872</value>
      <webElementGuid>1ce52441-0879-4408-9f2a-6c7b4a4c6ae7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
